from pathlib import Path
import json,re,subprocess,sys,html
P=Path(__file__).resolve().parents[1];D=P/'dist';V=Path('C:/Users/samir/Desktop/Attention-Aux-Encheres')
F='C:/Users/samir/Desktop/Agents-IA-Le-Film/work/tools/ffmpeg-9.0.2-essentials_build/bin/ffmpeg.exe'
subprocess.run([F,'-y','-v','error','-i',str(V/'Attention-Aux-Encheres.mp4'),'-c:v','libx264','-preset','fast','-crf','23','-c:a','aac','-b:a','160k','-movflags','+faststart',str(D/'media/attention.mp4')],check=True)
for w,suffix in [(720,''),(360,'-small')]:
 subprocess.run([F,'-y','-v','error','-i',str(V/'assets/auction.png'),'-vf',f'scale={w}:-1','-frames:v','1','-c:v','libwebp','-quality','86',str(D/f'assets/posters/attention{suffix}.webp')],check=True)
srt=(V/'Attention-Aux-Encheres.srt').read_text(encoding='utf-8');(D/'media/attention.vtt').write_text('WEBVTT\n\n'+re.sub(r'(\d{2}:\d{2}:\d{2}),(\d{3})',r'\1.\2',srt),encoding='utf-8')
film={'id':'attention','title':'Ton attention est à vendre.','category':'Culture numérique','color':'#dfff00','teaser':'Un commissaire-priseur, des applis et ton petit coup d’œil de vingt minutes.','description':'Une vente aux enchères absurde pour comprendre l’économie de l’attention, la publicité et le ciblage. Six images originales, trois voix françaises et une invitation à reprendre la main. La scène d’enchères est une fiction : on ne vend pas ton cerveau.','posterAlt':'Un commissaire-priseur en costume violet dans une salle d’enchères, téléphone exposé sous verre.','duration':49.183333,'durationLabel':'0:49','dateLabel':'8 octobre 2026','video':'media/attention.mp4','poster':'assets/posters/attention.webp','posterSmall':'assets/posters/attention-small.webp','captions':'media/attention.vtt','sources':'sources/attention.html','format':'FICTION + DÉCRYPTAGE','featured':True}
catalog=json.loads((D/'videos.json').read_text(encoding='utf-8'));catalog['videos']=[film]+[v for v in catalog['videos'] if v['id']!='attention'];(D/'videos.json').write_text(json.dumps(catalog,ensure_ascii=False,indent=2),encoding='utf-8')
(D/'sources/attention.html').write_text('''<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sources — Ton attention est à vendre</title><link rel="stylesheet" href="../style.css"></head><body><main class="wrap source-document"><a href="../">Retour à BRAINROT TV</a><p class="section-kicker">FICTION + DÉCRYPTAGE / 8 OCTOBRE 2026</p><h1>Ton attention est à vendre.</h1><p>La salle d’enchères, les personnages et les durées de trente secondes et vingt minutes sont fictifs. Les annonceurs peuvent participer à des enchères pour obtenir un placement publicitaire. Les pratiques de ciblage dépendent du service et des choix de l’utilisateur.</p><h2>Pour comprendre</h2><ul><li><a href="https://support.google.com/google-ads/answer/6366577?hl=fr" target="_blank" rel="noopener">Google Ads : comment fonctionne une mise aux enchères</a></li><li><a href="https://www.cnil.fr/fr/definition/publicite-ciblee" target="_blank" rel="noopener">CNIL : définition de la publicité ciblée</a></li><li><a href="https://www.cnil.fr/fr/cookies-et-autres-traceurs/regles/cookie-walls/publicite-ciblee-en-ligne-quels-enjeux-pour-la-protection-des-donnees-personnelles" target="_blank" rel="noopener">CNIL : publicité ciblée et protection des données</a></li></ul><h2>Réalisation</h2><p>HyperFrames, six illustrations originales générées par IA, trois voix françaises neurales, musique originale et sous-titres synchronisés. Durée : 49 secondes.</p></main></body></html>''',encoding='utf-8')
print('Attention added:',(D/'media/attention.mp4').stat().st_size,'bytes')
